### ISSUE TITLE
make a release version of IDO as one OWL file

### ISSUE THREAD

**Issue by zhengj2007** [infectious-disease-ontology/infectious-disease-ontology#46]
We use IDO and need to parse ido.owl and load it into the relation database. The release version of IDO import several OWL files and the imported OWL file also import other OWL files. It makes the loading quite difficult. I am wondering whether it is possible that IDO make a release version that merged all imported ontologies in one OWL file.

Thanks!

**Comment by lgcowell** [comment]
Hi Jie,

Thanks for the suggestion.  That’s a good idea.  I am not sure what is involved in doing that, but I will definitely look into it and update the list when we make the requested release.

Thanks!

Lindsay
— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by zhengj2007** [comment]
Thanks for your quick response. I think it is quite easy to use Protege 'refactor' menu 'merge ontologies ...' to merge all the import files in one OWL file.

**Comment by zhengj2007** [comment]
The merged file has been generated and PURL setting has been updated.
