### ISSUE TITLE
Requesting terms: 'passage process' & 'passage history record'

### ISSUE THREAD

**Issue by johnwjudkins** [infectious-disease-ontology/infectious-disease-ontology#5]
VEuPath had imported 'virus passage history record' from FLU, which also has the analogous  process term 'virus passage'. However, because that ontology is deprecated in OBO, and because 'virus passage' is specific to viruses, I would like to propose the addition of these more general terms:

'passage process': A material processing that consists of first growing an organism in an environmental system and then removing the organism to be grown in another environmental system, a process which may be repeated with the objective of altering the organism or increasing its number.

'passage history record': A data item that is about the sequence of environmental systems in each of which is grown an organism in a passage process.

Source: Wikipedia entry for "serial passage", Merriam-Webster medical definition for "passage"

**Comment by lgcowell** [comment]
Hi John,

We are happy to add these terms if IDO is the best place for them, but given how general they seem from the definition, I wonder if OBI isn’t a better fit. Copying a couple of OBI developers for their input.

Perhaps these more general terms can go in OBI and then we can include infectious agent-specific versions in IDO. Also, there are people working on a virus extension of IDO, so perhaps “virus passage” and the other virus-specific terms from flu could go there.

Thanks,

Lindsay

-------------------------------------------------------------------
Lindsay G. Cowell, PhD
Department of Population and Data Sciences
Department of Immunology
University of Texas Southwestern Medical Center at Dallas
5323 Harry Hines Blvd.
Dallas, TX  75390-9066

F4.212b, MC9066
phone: 214-648-2289
fax: 214-648-2064
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>

**Comment by johnwjudkins** [comment]
Thanks. I'm chairing the OBI-dev call tomorrow, so I put it on the agenda.

**Comment by johnwjudkins** [comment]
OBI has added 'passage process' and 'passage history record'. Closing.
